name: Manually deploy my-next-app on S3
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependecies
        run: npm ci

      - name: Build
        env:
          NOTION_SECERT_KEY: ${{ secrets.NOTION_SECERT_KEY }}
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 sync --region ${{ secrets.AWS_REGION }} ./out s3://${{ secrets.S3_BUCKET_NAME}}/ --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
